fix to support list of properties in propertysets[CMP-2659]
CloudBoltSoftware/onefuse-python-module pull request #15
Opened 2024-12-31 11:46 UTC by reach2shaik468

Property Toolkit to support OneFuse_CreateProperties_<custom-id> having an array/list of values.

2024-12-31 16:51 UTC, laltomar requested changes
LGTM, took me a few minutes to actually figure out what you were doing, please add some comments for future developers.

2024-12-31 16:51 UTC, laltomar commented on onefuse/admin.py
> +                elif isinstance(value_obj, dict) and "key" in value_obj and "value" in value_obj:
This code seems very hard to follow, a few comments describing what you are doing will go a long way for other developers.

2025-01-01 00:14 UTC, reach2shaik468 commented on onefuse/admin.py
> +                elif isinstance(value_obj, dict) and "key" in value_obj and "value" in value_obj:
I added the comments based on your suggestions. Thank you.

2025-01-02 13:56 UTC, laltomar approved these changes
LGTM!

2025-01-02 13:56 UTC, merged